name: dart_chatbot
description: A sample chat bot with dart and google_generative_ai package
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  envied: ^0.5.3
  google_generative_ai: ^0.2.1
# path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  lints: ^2.1.0
  test: ^1.24.0
